movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name = 'movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls', namespace='movieapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to ='gallery')
    overview = models.TextField()
    year = models.IntegerField()
    genre = models.CharField(max_length=100)
    rating = models.DecimalField(max_digits=2,decimal_places=1)
    
    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:                       #To include the fields from our model and render it within the same class, we use Meta
        model = Movie
        fields = ['name','image','overview','year','genre','rating']
        
      

movieproject/movieapp/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from . models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movielist' : movie
    }

    return render(request,'index.html',context)

def detail(request,movie_id):
    movie = Movie.objects.get(id = movie_id)                   #To get details of a particular id
    return render(request,'detail.html',{'movies' :movie})

def add_movie(request):
    if request.method == 'POST':                               #Fetching data from HTML FORM
        name = request.POST.get('name',)
        image = request.FILES['image']
        overview = request.POST.get('overview',)
        year = request.POST.get('year',)
        genre = request.POST.get('genre',)
        rating = request.POST.get('rating',)
        movie = Movie(name =name,image=image,overview = overview,year=year,genre= genre,rating=rating)      #Adding fetched data to database
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie = Movie.objects.get(id = id)
    form = MovieForm(request.POST or None, request.FILES,instance = movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method =='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')
    

movieproject/templates/add.html
{% extends 'base.html' %}

{% block body %}
 <form method="post" enctype="multipart/form-data" id="movie_details" style="text-align: center; font-size:x-large;">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name"><br>
    <input type="file" name="image"><br>
    <input type="text" name="overview" placeholder="Enter Storyline"><br>
    <input type="text" name="year" placeholder="Enter movie release year"><br>
    <input type="text" name="genre" placeholder="Enter Movie Genre"><br>
    <input type="text" name="rating" placeholder="Enter Movie Rating"><br>
    <input type='submit' value="Add Movie">
</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <!-- As a heading -->
        <nav class="navbar navbar-dark bg-dark">
            <span class="navbar-brand"> Online Movie Store</span>
        </nav>
        
            {% block body %}
            {%endblock%}
    </body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}

{% block body %}

<form method="post" style="color: red;">
    {%csrf_token %}
    <h1>Do you want to permanently delete this movie?</h1>
    <input type="submit" value="Yes, Delete!">

</form>

{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}

{%block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img src="{{movies.image.url}}" width="300" height="300"><br>
        </div>
        <div class="col-md-6" id="movie_details" style="font-size:x-large;">
            <h1>{{movies.name}} ({{movies.year}}) </h1>
            <p>{{movies.overview}}</p>
            <h6>Genre - {{movies.genre}}</h6>
            <h6>Rating - {{movies.rating}} / 10 </h6> <br><br>
            <a href="{% url 'movieapp:update' movies.id %}" class="btn btn-warning">Update movie</a>
            <a href="{% url 'movieapp:delete' movies.id %}" class="btn btn-warning">Delete movie</a>
        </div>
    </div>
</div>


{%endblock%}

movieproject/templates/edit.html
{% extends 'base.html' %}

{% block body %}

<form method="post" enctype="multipart/form-data" id="movie_details" style="text-align: center">
    {%csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update Movie">

</form>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container"> 
    <div class="row">  
        <div class="col-md-12 text-right">
            <a href="{% url 'movieapp:add_movie' %}" class="btn btn-success">Add New Movie</a>
        </div>
        {% for i in movielist %}
        <div class="col-md-4">            
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" width="200" height="250">
                <div class="card-body">
                  <h5 class="card-title">{{i.name }}</h5>
                  <p class="card-text"><strong>Price - 50 Rs.</strong></p>
                  <a href="{% url  'movieapp:detail'  i.id %}" class="btn btn-primary">About Movie</a>
                </div>
              </div>            
        </div>
        {%endfor%}
    </div>
</div>




{% endblock %}